[package]
name = "chat_server_tokio"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0"
tokio-util = { version = "0.7.13", features = ["full"] }