/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first terms will be:

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


// first let us do a brute force thing

fn main() {
    let mut sum = 0;

    let mut past = 1;
    let mut present = 1;

    let mut future = fib(past, present);

    while future < 4_000_000 {
        if future % 2 == 0 {
            sum += future;
            println!("Even number found: {}", future);
        }

        past = present;
        present = future;
        future = fib(past, present);
    }

    println!("The sum is {}", sum);
}


// calculate the fib number
fn fib(past: i32, present : i32) -> i32 {
    let future : i32 = past + present;
    future
}